"""empty message

Revision ID: 37942411d036
Revises: 728c21f9c70b
Create Date: 2020-06-01 17:04:26.706868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37942411d036'
down_revision = '728c21f9c70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('close_date')

    # ### end Alembic commands ###
